- package-lock.json
- package.json
- prisma/schema.prisma
- src/controllers/auth.controller.ts
- src/middlewares/auth.ts
- src/routes/auth.ts
- src/utils/index.ts
- src/utils/passport.ts
- src/utils/prisma.ts
Update user model to include first name and last name
Relating to issues 37, 30, 28 and 29
Yes
- [PR 42](https://github.com/hngx-org/Evento/pull/42)
Thank you for your review!
> Model Update

- package-lock.json
- package.json
- prisma/migrations/20231120100534_init/migration.sql
- prisma/schema.prisma
- src/controllers/user.controller.ts
- src/routes/user.controller.ts
​
This pull request includes changes to the User model and adds new routes for user profile and registration. The User model has been updated to include additional fields and the routes have been implemented to handle user profile retrieval and registration. These changes improve the functionality and usability of the application.
​
#4 
​
​
This has been tested with PostMan Extensively 
​
​
​
> Implement Get User Profile &&  added route

- prisma/migrations/20231120195156_init/migration.sql
- prisma/schema.prisma
- src/controllers/events.controller.ts
- src/interfaces/events.interface.ts
- src/routes/events.route.ts
- src/services/events.service.ts
**Feat: Implement create event endpoint**
​
Implement endpoint to create event
​
#7
​
This feature is needed to be able to create event
​
This has been tested with Postman
​
​
​
> Feat: Implement create event endpoint

- package-lock.json
- package.json
- prisma/migrations/20231120100800_update_model/migration.sql
- prisma/schema.prisma
- src/app.ts
- src/controllers/auth.controller.ts
- src/controllers/greetings.controller.ts
- src/middlewares/auth.ts
- src/routes/auth.ts
- src/services/generateSecretKey.ts
- src/services/slugify.ts
- src/utils/passport.ts
- src/utils/responsehandler.ts
- tsconfig.json
Update user model to include first name and last name
Relating to issues 37, 30, 28 and 29
Yes
- [PR 42](https://github.com/hngx-org/Evento/pull/42)
Thank you for your review!
> Updated SignUp and SignIn Controller

- src/controllers/user.controller.ts
- src/interfaces/user.interface.ts
- src/routes/user.route.ts
The task involves implementing the `/api/v1/user/profile/edit` endpoint to update user profile information. This versioned endpoint will allow users to modify their profile details.
- **Endpoint:** `/api/v1/user/profile/edit/:id`
- **HTTP Method:** PATCH
[Include a brief description of any specific issues or challenges related to the implementation of the User Profile Update endpoint.]
The User Profile Update endpoint should allow users to update their profile information, ensuring that the changes are accurately reflected.
#5 
Ensure the following best practices and conventions are followed during implementation:
Use endpoint as above with payload:
{
"bio": "",
"websiteURL": "",
"displayName": "",
"firstName": "",
"lastName": "",
"location": ""
}
[Include any additional information or …
> Implement-User-Profile-Update-Endpoint

- src/controllers/events.controller.ts
- src/interfaces/events.interface.ts
- src/routes/events.route.ts
**Feat: Implement edit events endpoint.**
​
I implemented the endpoint to update the fields of an event.
​
#8 
​
This feature allows users to update the fields of an event they created.
​
This has been tested with postman.
​
​
​
> Feat: Implement edit events endpoint 

- src/controllers/events.controller.ts
- src/routes/events.route.ts
**Feat: Implement get event endpoint.**
​
I implemented the endpoint to get an event by its ID.
​
#10 
​
This feature allows users to fetch details about an event.
​
This has been tested with postman.
​
* Get an event by ID:
​
​
> Feat: Implement get event endpoint

- src/controllers/events.controller.ts
- src/routes/events.route.ts
**Feat: Implement get all events route.**
​
I implemented the endpoint to retrieve all events.
​
#27 
​
This feature allows users to retrieve all events.
​
This has been tested with postman.
​
​
​
> Feat: Implement get all events route

- src/app.ts
- src/controllers/user.controller.ts
- src/interfaces/user.interface.ts
- src/routes/user.route.ts
This pull request implements the Add Social Links endpoint to the user profile API. Users can now add their social media links to their profiles. This feature enhances user engagement and allows users to share their social media presence with others.
Fixes #33
> Implement Add Social Links Endpoint

- src/controllers/user.controller.ts
- src/routes/user.route.ts
> Implement Social Links Retrieval Endpoint

- src/controllers/auth.controller.ts
- src/interfaces/user.interface.ts
- src/middlewares/auth.ts
- src/routes/auth.route.ts
- src/utils/passport.ts
Update user model to include first name and last name
Closes #28  and #29 
Yes
- [PR 42](https://github.com/hngx-org/Evento/pull/42)
Thank you for your review!
> Fix bug on auth

- package.json
> Revert "Highb33kay patch 1"

- package-lock.json
- package.json
This pull request updates the Node.js version requirement to ">=14.0.0" in the package.json file. This change ensures compatibility with the latest Node.js versions and allows developers to take advantage of new features and improvements.
> Update Node.js version requirement

- package-lock.json
This pull request fixes a bug in the login functionality of the application. The bug was causing users to encounter errors when attempting to log in. The issue has been identified and resolved, ensuring a smooth login experience for all users.
Fixes #1234
> Fix bug in login functionality

- src/routes/auth.route.ts
- src/routes/user.route.ts
This pull request refactors the documentation for the authentication and user routes. It improves the Swagger documentation by adding schemas for User, UserResponse, LoginCredentials, LoginResponse, Error, and AuthorizationResponse. It also updates the register and login routes to use the correct HTTP methods and fixes the callback URL for the Google authentication route. Additionally, it adds a new protected route that requires authentication using JWT.
> Refactor auth and user routes documentations

- src/controllers/user.controller.ts
- src/services/imageupload.ts
This pull request implements the Image Upload Service and User Control features. It includes the following changes:
- Added the `updateContactInformationByUserId` function to update contact information for a user.
- Added the `uploadProfilePicture` controller for uploading profile pictures.
- Imported necessary dependencies and error handling middleware.
- Updated the `getUserProfileById` and `updateUserProfileById` functions.
These changes enable users to update their contact information and upload profile pictures.
Fixes #1234
> Implement Image Upload Service and User Control

- src/interfaces/events.interface.ts
- src/routes/events.route.ts
**Docs: Document the events route.**
​
I documented the events route.
​
This feature implements the documentation for the events endpoints.
​
This has been tested with Swagger.
​
​
​
> Docs: Document the events route

- src/controllers/user.controller.ts
- src/routes/user.route.ts
- src/services/imageupload.ts
This pull request fixes an issue with file uploads and updates the Cloudinary configuration. The issue was causing errors when uploading profile images for users. The Cloudinary configuration has been updated to use environment variables for the cloud name, API key, and API secret. This ensures that sensitive information is not exposed in the code. The file upload route has also been refactored for better performance and error handling. This pull request addresses the following commits:
- Fix file upload issue and update Cloudinary configuration
- Refactor user profile image upload route
Fixes #1234
> Fix file upload issue and update Cloudinary configuration

- src/controllers/events.controller.ts
- src/routes/events.route.ts
**Feat: Implement delete event endpoint**
> Feat: Implement delete event endpoint

- src/controllers/auth.controller.ts
- src/routes/auth.route.ts
> Post for authorize endpoint

- src/utils/passport.ts
> fix user serialized into session

- src/controllers/user.controller.ts
This pull request includes the following changes:
- Added an email service and implemented sending welcome emails to new users
- Refactored the social links functionality
These changes address various features and issues in the codebase and improve the overall functionality of the application.
Fixes #4520
> Implement new features and fix issues

- prisma/migrations/20231202090538_preferences/migration.sql
- prisma/migrations/20231202091042_pref/migration.sql
- prisma/schema.prisma
- src/controllers/user.controller.ts
- src/interfaces/user.interface.ts
- src/routes/user.route.ts
This pull request updates the schema of the Preferences table. It drops the `notificationPreferences` column and recreates the `regionalSettings` column. The `theme` and `timeZone` columns are also added. Please note that this change will result in data loss for the `regionalSettings` column if there is any existing data.
> Update Preferences table schema

- src/app.ts
- src/routes/events.route.ts
**Chore: Remove authorization from get events route**
> Chore: Remove authorization from get events route

- prisma/migrations/20231204174145_verification/migration.sql
- prisma/schema.prisma
- src/app.ts
- src/controllers/auth.controller.ts
- src/controllers/user.controller.ts
- src/routes/user.route.ts
- src/services/mailer.ts
- src/utils/deletetoken.ts
- src/views/email/verify.html
This pull request includes updates to the email verification message and the addition of password update functionality. The email verification message has been modified to include a code for confirming login instead of a link. Additionally, a new endpoint has been added to update the user's password. These changes improve the security and user experience of the application.
> Update email verification message and add password update functionality

- src/controllers/auth.controller.ts
- src/controllers/user.controller.ts
- src/routes/auth.route.ts
- src/routes/user.route.ts
- src/views/email/verifypassword.html
This pull request fixes the authentication and password reset functionality in the codebase. It includes the following changes:
- Changed the HTTP method of the "/generate-otp/:id" route from GET to POST.
- Added a new route "/user/password/change/:id" to handle password updates.
- Added a new route "/user/password/confirm" to confirm password changes.
- Updated the "generateOTP" function to compare the provided email with the user's registered email.
- Updated the "updateUserPassword" function to generate a confirmation token and send a confirmation email.
- Added a new function "confirmPasswordChange" to handle password change confirmation.
These changes address the issues related to authentication and password reset functionality. Fixes #4520
> Fix authentication and password reset functionality

- src/routes/auth.route.ts
- src/routes/user.route.ts
This pull request adds the `confirmPasswordChange` route to the `auth.route.ts` file and removes it from the `user.route.ts` file. This change ensures that the `confirmPasswordChange` route is properly handled in the authentication flow.
> Add confirmPasswordChange route to auth.route.ts and remove confirmPasswordChange route from user.route.ts

- prisma/migrations/20231206041706_edit_event_and_ticket/migration.sql
- prisma/migrations/20231206051444_remove_time_column/migration.sql
- prisma/schema.prisma
- src/controllers/events.controller.ts
- src/interfaces/events.interface.ts
- src/routes/events.route.ts
**Refactor: Change how events are created.**
> Refactor: Change how events are created

- prisma/migrations/20231206220410_make_location_optional/migration.sql
- prisma/schema.prisma
- src/interfaces/events.interface.ts
**Chore: Make location field optional while creating events**
> Chore: Make location field optional while creating events

- src/routes/auth.route.ts
- src/views/email/verifypassword.html
**Changes Made:**
1. Update google end callback to return userId and token
Screenshots or images demonstrating the changes
- None
> Update google auth to return response

- src/controllers/auth.controller.ts
- src/routes/auth.route.ts
> update token for google auth

- src/routes/auth.route.ts
> Update redirect uri

- src/routes/auth.route.ts
> Update userId in cookies

- src/routes/auth.route.ts
> Fix redirect FE link

- src/routes/auth.route.ts
add redirect to dashboard after login
> add redirect to dashboard after login

- prisma/migrations/20231208144831_cover_image/migration.sql
- prisma/schema.prisma
- src/controllers/user.controller.ts
- src/routes/user.route.ts
- src/services/profileimage.ts
This pull request adds the functionality to upload and delete cover images for user profiles. It includes the following changes:
- Added a new column "coverImage" to the "User" table in the database.
- Created a new service function "uploadCoverImageService" to handle the upload of cover images.
- Created a new controller function "uploadProfileCoverImage" to handle the upload of cover images for a specific user.
- Added a new route "/api/v1/user/profile/cover/upload/{id}" to handle the upload of cover images.
- Created a new controller function "deleteUserCoverImage" to handle the deletion of cover images for a specific user.
- Added a new route "/api/v1/user/profile/cover/delete/{id}" to handle the deletion of cover images.
This functionality allows users to upload and delete cover …
> Add cover image upload and delete functionality

- src/routes/auth.route.ts
This pull request updates the redirect URL in the auth route to use the local development URL instead of the production URL. This change is necessary for testing and debugging purposes.
> Update redirect URL in auth route

- src/routes/events.route.ts
**[Chore: Make more routes RESTful](https://github.com/hngx-org/Evento/commit/3c6ca07f1b4038e6063424be54c35a09e694d384)**
> Chore: Make more routes RESTful

- src/routes/user.route.ts
This pull request updates the HTTP method from POST to PATCH for the "updateUserPassword" endpoint in the user router. This change ensures that the correct HTTP method is used for updating user passwords, improving the consistency and adherence to RESTful principles.
> Change HTTP method from POST to PATCH for updating user password

- prisma/migrations/20231212193414_userverification/migration.sql
- prisma/schema.prisma
- src/controllers/auth.controller.ts
- src/controllers/notifications.controller.ts
- src/middlewares/notification.ts
- src/routes/auth.route.ts
- src/routes/notifications.route.ts
- src/views/email/signupverified.mjml
Adding socket IO for notifications
> Adding socket IO for notifications

- package-lock.json
- package.json
- src/controllers/events.controller.ts
- src/interfaces/events.interface.ts
- src/middlewares/validations/events.zod.ts
- src/routes/events.route.ts
- tsconfig.json
**Feat: Implement Zod validations for events endpoints**
> Feat: Implement Zod validations for events endpoints

- package-lock.json
- package.json
- src/controllers/user.controller.ts
- src/middlewares/validationMiddleware.ts
- src/middlewares/validations/user.zod.ts
- src/routes/user.route.ts
- tsconfig.json
This pull request includes updates to the tsconfig.json and package.json files, as well as refactoring of the user controller and the addition of validation middleware to the user routes.
> Update tsconfig.json, package.json, user controller, and validation middleware

- src/controllers/auth.controller.ts
This pull request includes refactoring of email sending functions and fixing the URL in the reset password email. The changes ensure that the email sending functions are more efficient and that the URL in the reset password email directs users to the correct page.
> Refactor email sending functions and fix URL in reset password email

- package-lock.json
- package.json
- prisma/migrations/20231220110859_event_slug/migration.sql
- prisma/schema.prisma
- src/controllers/events.controller.ts
- src/middlewares/validations/user.zod.ts
This pull request updates the dependencies in the project and adds a new field called eventSlug to the Event table. The eventSlug field is a unique constraint and is required.
> Update dependencies and add eventSlug field

- src/controllers/events.controller.ts
- src/services/slugify.ts
This pull request updates the eventSlugify function in the code to handle event slugs. It replaces the existing slugify function with the eventSlugify function, which checks for existing events with the same slug and appends a number if necessary. This ensures that event slugs are unique and avoids conflicts.
> Update eventSlugify function to handle event slugs

- package-lock.json
- package.json
- prisma/migrations/20231219194823_add_event_slug/migration.sql
- prisma/schema.prisma
- src/controllers/events.controller.ts
- src/interfaces/events.interface.ts
- src/middlewares/validations/events.zod.ts
- src/routes/events.route.ts
- src/services/events.service.ts
**[Feat: Implement event slug, refactor events controller and validations](https://github.com/hngx-org/Evento/commit/3c5ddaac36a7a67d48f6b716e6be6cf3e294f707)**
> Feat: Implement event slug, refactor events controller and validations

- src/controllers/user.controller.ts
update signin to return isverified
> update signin to return isverified

- src/controllers/events.controller.ts
- src/middlewares/validations/user.zod.ts
This pull request adds the functionality to include participants in the registerForEventController and also adds validation checks for the event start date and capacity.
> Add include participants and validation checks in registerForEventController

- src/controllers/auth.controller.ts
Add access token to google signin
> Add access token to google signin

- src/controllers/auth.controller.ts
> Adding userId for new users

- src/middlewares/validations/events.zod.ts
**[Bug: Fix location enforcement bug](https://github.com/hngx-org/Evento/commit/fdca1c5665413bc229ea23d12235d17fbe1d8538)**
> Bug: Fix location enforcement bug

- src/controllers/events.controller.ts
- src/routes/events.route.ts
This pull request adds a new deleteEventsController to the events.controller and events.route files. The deleteEventsController handles the deletion of events and their related tickets.
> Add deleteEventsController to events.controller and events.route
